In [1]:
import numpy as np
print(np.__version__)

1.21.5


In [4]:
a=[1,2,3,4,5,6,7,8,9]
numpyarry=np.array(a)
print(numpyarry)
numpyarry

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c=numpyarry+2
print(c)

[ 3  4  5  6  7  8  9 10 11]


In [6]:
c=numpyarry-2
print(c)

[-1  0  1  2  3  4  5  6  7]


In [7]:
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(a+b)

[6 6 6 6 6]


In [8]:
a=[1, 2, 3, 4, 5, 6, 7, 8, 9]
na=np.array(a)
na.shape

(9,)

In [11]:
a=[[1, 2, 3], [4, 5, 6],[7, 8, 9]]
na=np.array(a)
print(na.shape)

(3, 3)
